### ISSUE TITLE
npm install && npm start (when pressing the login button)

### ISSUE THREAD

**Issue by kennblvnp** [viniarruda/react-boilerplate#10]
at `./src/views/home/index.js`

> Line 16:6:  React Hook useEffect has missing dependencies: 'product.list' and 'setListProducts'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

**Comment by kennblvnp** [comment]
I support react hooks and context :D

**Comment by viniarruda** [comment]
Oh, sorry for delay. I will adjust this. Thanks !

**Comment by viniarruda** [comment]
Fix Done 😃
